name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-action:
    name: Run action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run my action
        uses: ./.github/actions/helperFunctions

        with:
          name: "This Dot Labs"
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Shell check
        run: |
          echo in shell check
          echo PWD :
          pwd
          echo LS :
          ls
          echo shell check end
