name: Upload and download files to.from Jfrog Artifactory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: jfrog/setup-jfrog-cli@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Add permission to gradle
      run: chmod +x gradlew

    - name: Build gradle project
      run: ./gradlew build -x test

    # connects to JFrog CLI with artifactory url and access token (access token can be created in JFrog control panel
    - name: Log into JFrog Artifactory
      run: |
        jf c add kermit --artifactory-url=${{ secrets.JF_ARTIFACTORY_SERVER_URL }} --access-token=${{ secrets.JF_ACCSESS_TOKEN }}

    # upload all files under /build to "example-repo-local" repository in artifactory
    # can also specify regex for files to upload or upload single file - for more info go to  JFrog repository documentation
    # https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory
    - name: Upload all build files to repository
      run: |
        jf rt upload "build/" example-repo-local

    # upload only jars "upload all" - from shared libraries
    - name: Upload jars to different repository
      run: |
        jf rt upload "build/*.jar" my-project-jars-gradle-dev-local

      # download uploaded jars
    - name: Download jars from repository
      run: |
        jf rt download my-project-jars-gradle-dev-local my-jars/

    # echo downloaded files
    - name: Show downloaded files
      run: |
        ls ${{ github.workspace }}/my-jars/build/libs