# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Send test report

# events on which trigger workflow
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# job is a chain of actions
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     every action is github repo, checkout: https://github.com/actions/checkout/blob/main/action.yml
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

# for maven project we will need different steps
    - name: Add permission to gradle
      run:  chmod +x gradlew

    - name: Run tests with gradle
      continue-on-error: true
      run: ./gradlew test

    - name: Generate test report
      id: test_report
      uses: ./.github/actions/testReport
      with:
#        just sample link to show that it works
        heroldUrl: 'https://www.google.com/'
#        gradle test report path (for maven project probably we will need another path here)
        path: '/home/runner/work/actions-test/actions-test/build/test-results/test'
        header1: 'Junit Tests'
        header2: 'Made for test project'
        header3: 'Run using gradle'
        failedTestProjects: 'some testsuite,another one, one more'

# 3rd party action - but used by lots of people, I looked into code, there is nothing suspicious there.
# If we need we can create own send mailaction but I think it's not needed
    - name: Send email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        # Optional port (defaults to 465)
        server_port: 465
#       send email from account set in github repo to itself, just to show it works
        username:  ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        from: ${{secrets.ACCOUNT}}
        to: ${{secrets.ACCOUNT}}
        subject: Test report
#       html output from previous step is used here
        html_body: ${{ steps.test_report.outputs.html }}
        secure: true